### ISSUE TITLE
missing possibility to disable menubar-behaviour

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-tweaks#4]
If I change in `xitweaks.conf` from this:
```
menubar_hide_on_start=false
menubar_restore_state=false
menubar_previous_state=true
```
to this:
```
menubar_hide_on_start=true
menubar_restore_state=false
menubar_previous_state=false
```
then after every restart of Geany I see for a part of a second the menu-bar.

Comparison
If I use the scripts of https://github.com/xiota/geanylua-scripts, then I don't see for a part of a second the menu-bar.

Possible solution
Either tweaks should be as good as the scripts of https://github.com/xiota/geanylua-scripts, or in xitweaks.conf there should be the possibility to disable the menubar-behaviour with something like `menubar-behaviour=false`, so that the scripts of https://github.com/xiota/geanylua-scripts work.

Additional Remarks
1
It would be good to mention for all three values in the comment the default setting for each value (same for the value sidebar_focus_enabled).
2
It would be good to mention in the comment if only one of the three values should be set to true.
3
For what `menubar_restore_state` is standing for? An explication in the comment would be good.
4
It would be superb if this issue would be fixed soon.

**Comment by xiota** [comment]
Geany starts with the menubar visible.  Then the plugin hides it when loaded.  There may be some timing difference between when GeanyLua and the tweaks plugins load.

Are you running GeanyLua and xitweaks at the same time?  Is this the version of tweaks that fiddles with sidebar highlighting?

**Comment by ralf3u** [comment]
> Are you running GeanyLua and xitweaks at the same time?

No. In the Plugin-Manager either GeanyLua is activated or Xi/Tweaks, so that there is no overlap between GeanyLua and Xi/Tweaks. GeanyLua runs absolutely perfect: On every restart of Geany the menu-bar is not visible at all. So I'm very satisfy with this plugin. But in Xi/Tweaks I see for a part of a second the menu-bar. And that is the reason why I would like to disable the behavior of the menu-bar in Xi/Tweaks with something like menu-bar_behavior=false. And then I would use both plugin at the same time. If now I use both plugin at the same time, then there is some artifact in that way, that sometimes I have to press two times the shortcut toggle menu-bar to let disappear the menu-bar.

> Is this the version of tweaks that fiddles with sidebar highlighting?

I use the tweaks for changing the color of the tab-title of the sidebar when the tab is in focus (when the shortcut is used to toggle editor/sidebar or when clicking on the tab-title of the sidebar).

**Comment by ralf3u** [comment]
possible solution
I think that the easiest way to fix this issue would be if all three values could be set to false, just like this:
```
menubar_hide_on_start=false
menubar_restore_state=false
menubar_previous_state=false
```
At the moment it is not possible, because if I do it, then after a restart of Geany there is this: `menubar_previous_state=true`

**Comment by xiota** [comment]
@ralf3u Would it be fine with you if I just remove menubar hiding from this plugin?  Then this plugin (maybe to be renamed) will only try to highlight the sidebar tab.

I've already moved menubar hiding and other features (except sidebar tab highlighting) that were formerly part of this plugin to another plugin.

**Comment by ralf3u** [comment]
> Would it be fine with you if I just remove menubar hiding from this plugin? Then this plugin (maybe to be renamed) will only try to highlight the sidebar tab.

It would be the best-case-scenario for me.

**Comment by ralf3u** [comment]
It would be great if the changed plugin comes with the latest Geany version, because I reported a bug in geany-plugins, the plugin "Spell Check", and the maintainer solved it some days ago and asked me to test it (issue number 1158).

**Comment by ralf3u** [comment]
>Would it be fine with you if I just remove menubar hiding from this plugin? Then this plugin (maybe to be renamed) will only try to highlight the sidebar tab.

If you would do that, then this plugin is only about highlighting. But then, why you don't integrate the code in Geany Preview? A part of it was once in Geany Preview:
https://github.com/xiota/geany-preview/issues/5#issuecomment-939276888

**Comment by xiota** [comment]
The problem is the highlighting doesn't work perfectly.  There's stuff going on with the GUI I don't know about or the API is missing needed calls (probably both).  If it ever works properly, I would probably move it to the other tweaks plugin.

**Comment by ralf3u** [comment]
> The problem is the highlighting doesn't work perfectly.

The only thing what does not work is, if one click in the content-tab of the sidebar (what works is shortcut toggle editor/sidebar and clicking on the tab-title). In Geany Preview in issue number 5 you meant something like there is no signal if the content area is in focus:
>The problem is I need to get signals from the widget to respond to. Without a signal, there's no way to know when something is clicked or has focus or whatever.

So my idea is to open in Geany an issue with something like this: "no signal if sidebar is in focus" and if the maintainer of Geany could add a signal to know if sidebar is in focus, so the issue in Geany Preview could maybe be fixed in the future. Then maybe also Geany Preview issue number 15 could be fixed. What you think about that?

**Comment by xiota** [comment]
The problem is probably not Geany.  It's probably GTK or that I don't know how to use GTK.

**Comment by ralf3u** [comment]
>The problem is probably not Geany.

"Probably" could be ruled out if you report it to Geany. I'm convinced that the maintainers of Geany are able to tell you if it is a Geany problem or not. Maybe they will give you an interesting hint. It is better if you open an issue in Geany, because I don't know anything about how to program a software. The best case is if the issue in Geany is about to try to solve issue number 5 and issue number 15 of Geany Preview.

For me the highlighting is an essential feature of Geany Preview. It's cool, it's useful and it gives joy. It's a pity that it does not work perfect.

**Comment by xiota** [comment]
Are you still using 21.04?  The PPA won't update anymore because 21.04 has reached end of life.  I haven't decided when to remove the 21.04 packages.  22.04 is around the corner, so don't know if it's worth switching to 21.10 right now.

**Comment by ralf3u** [comment]
> 22.04 is around the corner ...

Yes, you are right. For 22.04 would be good. It is in exactly two months.

**Comment by xiota** [comment]
I updated the PPA for 18.04, 20.04, and 21.10.  On even numbered years, the first release is LTS (long term support) supported for 5 years.  All other releases are supported for 9 months.  So support for 21.04 ended.  End of support also means that the PPA won't build packages for that release anymore.  You can go to the PPA webpage to manually download and install the packages for one of the other releases.  It's not guaranteed to work though.

**Comment by ralf3u** [comment]
> I updated the PPA for 18.04, 20.04, and 21.10.

I did an update on Lubuntu 21.10. But toggle menu-bar is still part of xitweaks.conf. And I don't know if you updated also geany-plugins, but I don't have the latest geany-plugins. In help, it says that Geany 1.39 was compiled in December 30 or later.

**Comment by ralf3u** [comment]
@xiota
I can confirm that now after every restart of Geany I don't see any more for a part of a second the menu-bar. So, the issue is fixed. Thank you so much.

Nevertheless it would be good if the following code is not any more in xitweaks.conf:
```
# The following options controls whether the menubar is hidden.
# Set a keybinding in preferences to change menubar visibility.
menubar_hide_on_start=false
menubar_restore_state=false
menubar_previous_state=true
```

This is the reason why I don't close this issue.

**Comment by xiota** [comment]
Thanks for the reminder.  I'll update the PPA.
