### ISSUE TITLE
update for 22.04

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-tweaks#5]
On https://launchpad.net/~xiota/+archive/ubuntu/geany-plugins I can't see updates for Xi/Tweaks and for Preview for Lubuntu 22.04.
Would it be also possible to add to the PPA of Preview the latest Geany and the latest Geany plugins?

**Comment by xiota** [comment]
A bunch of stuff doesn't compile in 22.04, and I haven't bothered to figure out why yet.

You can still use the 21.10 builds for now.  Edit the appropriate file in `/etc/apt/sources.list.d/` to add:

    deb http://ppa.launchpad.net/xiota/stuff-21.10/ubuntu impish main

**Comment by ralf3u** [comment]
I install Lubuntu 22.04. After the installation of Geany I execute those lines in the terminal:
```
sudo add-apt-repository ppa:xiota/geany-plugins
sudo apt-get update
sudo apt-get install geany-plugin-preview geany-plugin-xi-tweaks
```
And then I edit the document mentioned in https://github.com/xiota/geany-tweaks/issues/5#issuecomment-1107942310. Then I save the changed document.

Is that correct? Should I do an update afterwards or something like this, so that the changed document will be executed?

**Comment by xiota** [comment]
I've finally updated the PPA for jammy (22.04).  Please let me know if there are any problems.  Thank you for your patience.

**Comment by xiota** [comment]
What happens if you use `sudo apt` instead of `sudo apt-get`?

**Comment by ralf3u** [comment]
>What happens if you use sudo apt instead of sudo apt-get?

```
sudo add-apt-repository ppa:xiota/geany-plugins
sudo apt update
sudo apt install geany-plugin-preview
```

Answer of the terminal:
`Warten auf Sperre für Zwischenspeicher: Sperre /var/lib/dpkg/lock-frontend konnte nicht erlangt werden. Sie wird von Prozess 16741 (unattended-upgr) gehalten.Warten auf Sperre für Zwischenspeicher: Sperre /var/lib/dpkg/lock-frontend konnte nicht erlangt werden. Sie wird von Prozess 16741 (unattended-upgr) gehalten.`
And then same answer, something like:
The following packages have unfulfilled dependencies:
geany preview:
depending from: libcmark-gfm0 but can not be installed
depending from: libcmark-gfm-extensions0 but can not be installed
E: Issues cannot be corrected, you have held back broken packages.

Geany Preview does not appear in the list of plugins in Geany.

**Comment by xiota** [comment]
Please try:
```
sudo add-apt-repository --remove ppa:xiota/geany-plugins
sudo add-apt-repository ppa:xiota/geany-plugins
```

**Comment by ralf3u** [comment]
This is what I did:
```
sudo add-apt-repository --remove ppa:xiota/geany-plugins
sudo add-apt-repository ppa:xiota/geany-plugins
sudo apt update
sudo apt install geany-plugin-preview
```
But the answer is still the same.

**Comment by xiota** [comment]
Strange...  I don't have this problem.  It may take some time to figure out what's wrong.  Thank you for your patience.

**Comment by xiota** [comment]
I just updated the PPA.  Should work now.  Please let me know.

**Comment by ralf3u** [comment]
I just did an update. Now everything works. Thank you so much.
